guide_homepage:
    pattern:  /
    defaults: { _controller: WerGuideBundle:Main:index }
guide_manager:
    pattern: /manager/
    defaults: { _controller: WerGuideBundle:Manager:index }
guide_manager_field:
    pattern: /manager/field/
    defaults: { _controller: WerGuideBundle:Manager:field }
