guide_homepage:
    path:  /
    defaults: { _controller: WerGuideBundle:Main:index }
guide_item:
    path: /item/{item_id}/
    defaults: { _controller: WerGuideBundle:Item:index }
guide_item_wrong:
    path: /item/
    defaults: { _controller: WerGuideBundle:Main:index }
guide_manager:
    path: /manager/
    defaults: { _controller: WerGuideBundle:Manager:index }
guide_manager_field:
    path: /manager/field/
    defaults: { _controller: WerGuideBundle:Manager:field }
guide_search:
    path: /search/
    defaults: { _controller: WerGuideBundle:Search:quickForm }
    methods: [GET]
guide_search_process:
    path: /search/
    defaults: { _controller: WerGuideBundle:Search:index }
    methods: [POST]
guide_search_advanced:
    path: /search/advanced/
    defaults: { _controller: WerGuideBundle:Search:advanced }
    methods: [GET]
guide_search_advanced_process:
    path: /search/advanced/
    defaults: { _controller: WerGuideBundle:Search:advancedSearch }
    methods: [POST]
guide_search_alpha_oops:
    path: /search/by_alpha/
    defaults: { _controller: WerGuideBundle:Search:by_alpha }
guide_search_alpha:
    path: /search/by_alpha/{the_letter}/
    defaults: { _controller: WerGuideBundle:Search:by_alpha }
guide_search_alpha_nextprevious:
    path: /search/by_alpha/{the_letter}/{start}/
    defaults: { _controller: WerGuideBundle:Search:by_alpha }
guide_search_alpha_more:
    path: /search/by_alpha/{the_letter}/{start}/{number}/
    defaults: { _controller: WerGuideBundle:Search:by_alpha }
guide_search_section:
    path: /search/bySection/{sec_id}/
    defaults: { _controller: WerGuideBundle:Search:bySection }
guide_search_category:
    path: /search/byCategory/{cat_id}/
    defaults: { _controller: WerGuideBundle:Search:byCategory }
guide_test_item:
    path: /test/item/
    defaults: { _controller: WerGuideBundle:Tests:item }
