guide_homepage:
    pattern:  /
    defaults: { _controller: WerGuideBundle:Main:index }
guide_manager:
    pattern: /manager/
    defaults: { _controller: WerGuideBundle:Manager:index }
guide_manager_field:
    pattern: /manager/field/
    defaults: { _controller: WerGuideBundle:Manager:field }
guide_search:
    pattern: /search/
    defaults: { _controller: WerGuideBundle:Search:index }
guide_search_advanced:
    pattern: /search/advanced/
    defaults: { _controller: WerGuideBundle:Search:advanced }
guide_search_alpha:
    pattern: /search/byAlpha/
    defaults: { _controller: WerGuideBundle:Search:byAlpha }
guide_search_section:
    pattern: /search/bySection/
    defaults: { _controller: WerGuideBundle:Search:bySection }
guide_search_category:
    pattern: /search/byCategory/
    defaults: { _controller: WerGuideBundle:Search:byCategory }
guide_display_item:
    pattern: /display/item/
    defaults: { _controller: WerGuideBundle:Main:displayItem }
