Wer\SobiBundle\Entity\SobiConfig:
  type: entity
  table: sobi_config
  fields:
    configkey:
      id: true
      type: string
      length: 100
      fixed: false
      nullable: false
      column: configKey
    sobi2section:
      id: true
      type: string
      length: 100
      fixed: false
      nullable: false
      column: sobi2Section
    configvalue:
      type: text
      nullable: true
      column: configValue
    description:
      type: text
      nullable: true
  lifecycleCallbacks: {  }
