Wer\SobiBundle\Entity\SobiFieldsData:
  type: entity
  table: sobi_fields_data
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    fieldid:
      type: integer
      unsigned: false
      nullable: true
    dataTxt:
      type: text
      nullable: true
      column: data_txt
    dataBool:
      type: boolean
      nullable: true
      column: data_bool
    dataInt:
      type: integer
      unsigned: false
      nullable: true
      column: data_int
    dataFloat:
      type: float
      nullable: true
      column: data_float
    dataChar:
      type: string
      length: 255
      fixed: false
      nullable: false
      column: data_char
    itemid:
      type: integer
      unsigned: false
      nullable: true
    expiration:
      type: datetime
      nullable: true
  lifecycleCallbacks: {  }
