Wer\SobiBundle\Entity\WerFieldOption:
  type: entity
  table: wer_field_option
  fields:
    foId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: fo_id
      generator:
        strategy: IDENTITY
    foFieldOption:
      type: text
      nullable: false
      column: fo_field_option
  manyToOne:
    foField:
      targetEntity: WerField
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        fo_field_id:
          referencedColumnName: field_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
