Wer\SobiBundle\Entity\WerField:
  type: entity
  table: wer_field
  fields:
    fieldId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: field_id
      generator:
        strategy: IDENTITY
    fieldName:
      type: text
      nullable: false
      column: field_name
    fieldEnabled:
      type: boolean
      nullable: false
      column: field_enabled
  manyToOne:
    fieldType:
      targetEntity: WerFieldTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        field_type_id:
          referencedColumnName: ft_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
