Wer\SobiBundle\Entity\WerSectionCategory:
  type: entity
  table: wer_section_category
  fields:
    scId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: sc_id
      generator:
        strategy: IDENTITY
  manyToOne:
    scCategory:
      targetEntity: WerCategory
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        sc_category_id:
          referencedColumnName: cat_id
      orphanRemoval: false
    scSection:
      targetEntity: WerSection
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        sc_section_id:
          referencedColumnName: sec_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
