<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Ritc\Library\Abstracts\Base'                => __DIR__ . '/../Library/Abstacts/Base.php',
  'Ritc\Library\Abstracts\Tester'              => __DIR__ . '/../Library/Abstacts/Tester.php',
  'Ritc\Library\Core\Access'                   => __DIR__ . '/../Library/Core/Access.php',
  'Ritc\Library\Core\Actions'                  => __DIR__ . '/../Library/Core/Actions.php',
  'Ritc\Library\Core\Arrays'                   => __DIR__ . '/../Library/Core/Arrays.php',
  'Ritc\Library\Core\Autoload'                 => __DIR__ . '/../Library/Core/Autoload.php',
  'Ritc\Library\Core\Config'                   => __DIR__ . '/../Library/Core/Config.php',
  'Ritc\Library\Core\Database'                 => __DIR__ . '/../Library/Core/Database.php',
  'Ritc\Library\Core\DatesTimes'               => __DIR__ . '/../Library/Core/DatesTimes.php',
  'Ritc\Library\Core\DbFactory'                => __DIR__ . '/../Library/Core/DbFactory.php',
  'Ritc\Library\Core\Elog'                     => __DIR__ . '/../Library/Core/Elog.php',
  'Ritc\Library\Core\Files'                    => __DIR__ . '/../Library/Core/Files.php',
  'Ritc\Library\Core\Html'                     => __DIR__ . '/../Library/Core/Html.php',
  'Ritc\Library\Core\Location'                 => __DIR__ . '/../Library/Core/Location.php',
  'Ritc\Library\Core\Session'                  => __DIR__ . '/../Library/Core/Session.php',
  'Ritc\Library\Core\Strings'                  => __DIR__ . '/../Library/Core/Strings.php',
  'Ritc\Library\Core\Tail'                     => __DIR__ . '/../Library/Core/Tail.php',
  'Ritc\Library\Helper\ViewHelper'             => __DIR__ . '/../Library/Helper/ViewHelper.php',
  'Ritc\Library\Interfaces\DbAdminInterface'   => __DIR__ . '/../Library/Interfaces/DbAdminInterface.php',
  'Ritc\Library\Interfaces\DbSuAdminInterface' => __DIR__ . '/../Library/Interfaces/DbSuAdminInterface.php',
);
