<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Ritc\Framework\Helper\ViewHelper'          => __DIR__ . '/../Framework/Helper/ViewHelper.php',
    'Ritc\Framework\Library\Access'             => __DIR__ . '/../Framework/Library/Access.php',
    'Ritc\Framework\Library\Actions'            => __DIR__ . '/../Framework/Library/Actions.php',
    'Ritc\Framework\Library\Arrays'             => __DIR__ . '/../Framework/Library/Arrays.php',
    'Ritc\Framework\Library\Base'               => __DIR__ . '/../Framework/Library/Base.php',
    'Ritc\Framework\Library\Config'             => __DIR__ . '/../Framework/Library/Config.php',
    'Ritc\Framework\Library\Database'           => __DIR__ . '/../Framework/Library/Database.php',
    'Ritc\Framework\Library\Date_Time'          => __DIR__ . '/../Framework/Library/Date_Time.php',
    'Ritc\Framework\Library\Elog'               => __DIR__ . '/../Framework/Library/Elog.php',
    'Ritc\Framework\Library\Files'              => __DIR__ . '/../Framework/Library/Files.php',
    'Ritc\Framework\Library\HTML'               => __DIR__ . '/../Framework/Library/Html.php',
    'Ritc\Framework\Library\Location'           => __DIR__ . '/../Framework/Library/Location.php',
    'Ritc\Framework\Library\Session'            => __DIR__ . '/../Framework/Library/Session.php',
    'Ritc\Framework\Library\Strings'            => __DIR__ . '/../Framework/Library/Strings.php',
    'Ritc\Framework\Library\Tail'               => __DIR__ . '/../Framework/Library/Tail.php',
    'Ritc\Framework\Library\Tester'             => __DIR__ . '/../Framework/Library/Tester.php',
    'Ritc\Framework\Library\RitcAutoloader'      => __DIR__ . '/../Framework/Library/RitcAutoloader.php',
);
