parameters:
#    wer_sobi2.example.class: Wer\SobiBundle\Example

services:
#    wer_sobi2.example:
#        class: %wer_sobi2.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
