WerCategory:
  type: entity
  table: wer_category
  fields:
    cat_id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: cat_id
      generator:
        strategy: IDENTITY
    cat_name:
      type: text
      nullable: false
      column: cat_name
    cat_description:
      type: text
      nullable: false
      column: cat_description
    cat_icon:
      type: text
      nullable: false
      column: cat_icon
    cat_active:
      type: boolean
      nullable: false
      column: cat_active
  manyToMany:
    cr_parent_id:
      type: integer
      targetEntity: WerCategory
      mappedBy: cr_child_id
    cr_child_id:
      targetEntity: WerCategory
      inversedBy: cr_parent_id
      joinTable:
        name: wer_category
        joinColumns:
          cr_parent_id:
            referencedColumnName: cat_id
        inverseJoinColumns:
          cr_child_id:
            referencedColumnName: cat_id
  lifecycleCallbacks: {  }
