WerFieldTypes:
  type: entity
  table: wer_field_types
  fields:
    ft_id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: ft_id
      generator:
        strategy: IDENTITY
    ft_name:
      type: text
      nullable: false
      column: ft_name
    ft_type:
      type: text
      nullable: false
      column: ft_type
  lifecycleCallbacks: {  }
