WerSection:
  type: entity
  table: wer_section
  fields:
    sec_id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: sec_id
      generator:
        strategy: IDENTITY
    sec_name:
      type: text
      nullable: false
      column: sec_name
    sec_description:
      type: text
      nullable: false
      column: sec_description
    sec_active:
      type: boolean
      nullable: false
      column: sec_active
  lifecycleCallbacks: {  }
