parameters:
#    wer_guide.example.class: Wer\GuideBundle\Example

services:
#    wer_guide.example:
#        class: %wer_guide.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
