SobiFields:
  type: entity
  table: sobi_fields
  fields:
    fieldid:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    fieldtype:
      type: integer
      unsigned: false
      nullable: true
      column: fieldType
    wysiwyg:
      type: boolean
      nullable: true
    fielddescription:
      type: text
      nullable: true
      column: fieldDescription
    explanation:
      type: text
      nullable: true
    isFree:
      type: boolean
      nullable: true
      column: is_free
    payment:
      type: float
      nullable: true
    fieldchars:
      type: integer
      unsigned: false
      nullable: true
      column: fieldChars
    fieldrows:
      type: integer
      unsigned: false
      nullable: true
      column: fieldRows
    fieldcolumns:
      type: integer
      unsigned: false
      nullable: true
      column: fieldColumns
    preferredSize:
      type: integer
      unsigned: false
      nullable: true
      column: preferred_size
    cssclass:
      type: text
      nullable: true
      column: CSSclass
    enabled:
      type: boolean
      nullable: true
    iseditable:
      type: boolean
      nullable: true
      column: isEditable
    isRequired:
      type: boolean
      nullable: true
      column: is_required
    inPromoted:
      type: boolean
      nullable: true
      column: in_promoted
    inVcard:
      type: boolean
      nullable: true
      column: in_vcard
    inDetails:
      type: boolean
      nullable: false
      column: in_details
    position:
      type: integer
      unsigned: false
      nullable: true
    inSearch:
      type: integer
      unsigned: false
      nullable: false
      column: in_search
    withLabel:
      type: boolean
      nullable: false
      column: with_label
    inNewline:
      type: boolean
      nullable: false
      column: in_newline
    isurl:
      type: integer
      unsigned: false
      nullable: false
      column: isUrl
    checkedOut:
      type: integer
      unsigned: false
      nullable: false
      column: checked_out
    checkedOutTime:
      type: datetime
      nullable: false
      column: checked_out_time
    displayed:
      type: boolean
      nullable: false
  lifecycleCallbacks: {  }
