WerFieldTypes:
  type: entity
  table: wer_field_types
  fields:
    ftId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: ft_id
      generator:
        strategy: IDENTITY
    ftName:
      type: text
      nullable: false
      column: ft_name
    ftType:
      type: text
      nullable: false
      column: ft_type
  lifecycleCallbacks: {  }
