WerObjectData:
  type: entity
  table: wer_object_data
  fields:
    odId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: od_id
      generator:
        strategy: IDENTITY
    odData:
      type: text
      nullable: false
      column: od_data
    odCreatedOn:
      type: datetime
      nullable: false
      column: od_created_on
    odUpdatedOn:
      type: datetime
      nullable: false
      column: od_updated_on
  manyToOne:
    odObject:
      targetEntity: WerObject
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        od_object_id:
          referencedColumnName: obj_id
      orphanRemoval: false
    odField:
      targetEntity: WerField
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        od_field_id:
          referencedColumnName: field_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
